# примеры API-запросов

@baseUrl = http://localhost:8000

# Загрузить данные из магазина
POST {{baseUrl}}/upload/
Content-Type: application/json

{
  "url": "http://gw36.a-don.ru:8181/platform/shop1.yaml"
}

###

# Создание пользователя
POST  {{baseUrl}}/createuser/
Content-Type: application/json

{
  "password": "test"
}

###

# получение путь и имя файла
GET {{baseUrl}}/processed/b20743dc-c374-451c-8ee5-aa04df1520fc.png
Content-Type: application/json