# примеры API-запросов

@baseUrl = http://localhost:8000

# Загрузить данные из магазина
POST {{baseUrl}}/upload/
Content-Type: application/json
Authorization: Token d51638d2f34431708b9e1271744edde7a9a3c70f

{
  "url": "http://gw36.a-don.ru:8181/platform/shop1.yaml"
}

###

# Создание пользователя
POST  {{baseUrl}}/createuser/
Content-Type: application/json

{
  "surname": "Ivanov",
  "first_name": "Ivan",
  "last_name": "Ivanovich",
  "email": "with@ya.ru",
  "password": "test",
  "confirm_password": "test",
  "company": "IP Ivanov",
  "position": "CEO"

}

###

# Вход
POST {{baseUrl}}/enter/
Content-Type: application/json

{
  "email": "Nik@ya.ru",
  "password": "test"
}

###

# Список всех товаров
GET {{baseUrl}}/products/4216292
Content-Type: application/json

###

# карточка товара
GET {{baseUrl}}/api/productcard/4216292
Content-Type: application/json