# примеры API-запросов

@baseUrl = http://localhost:8000

# Загрузить данные из магазина
POST {{baseUrl}}/upload/
Content-Type: application/json
Authorization: Token aa233d4314397c16eacb0bf09d1a139864a4ffa1

{
  "url": "http://gw36.a-don.ru:8181/platform/shop1.yaml"
}

###

# Создание пользователя
POST  {{baseUrl}}/createuser/
Content-Type: application/json

{
  "surname": "Ivanov",
  "first_name": "Ivan",
  "last_name": "Ivanovich",
  "email": "Iva@ya.ru",
  "password": "test",
  "confirm_password": "test",
  "company": "IP Ivanov",
  "position": "CEO"

}

###

# Вход
POST {{baseUrl}}/enter/
Content-Type: application/json

{
  "email": "Ivan@ya.ru",
  "password": "test"
}

###

# Список всех товаров
GET {{baseUrl}}/products/
Content-Type: application/json

###

# карточка товара
GET {{baseUrl}}/productcard/4216313
Content-Type: application/json
Authorization: Token 792e208807fc178be958c8773507828b8be5e8ce

###

# карточка товара с фильтром по магазину
GET   {{baseUrl}}/productcard/4216313/?shop=Связной
Content-Type: application/json
Authorization: Token 792e208807fc178be958c8773507828b8be5e8ce

###

# Создать заказ
POST {{baseUrl}}/order/
Content-Type: application/json
Authorization: Token aa233d4314397c16eacb0bf09d1a139864a4ffa1

###

# Посмотреть заказ
GET {{baseUrl}}/order/2/
Content-Type: application/json
Authorization: Token aa233d4314397c16eacb0bf09d1a139864a4ffa1

###

# Изменение статуса заказа
PATCH {{baseUrl}}/order/2/
Content-Type: application/json
Authorization: Token aa233d4314397c16eacb0bf09d1a139864a4ffa1

{
  "status": "canceled"
}


###

# Положить в корзину товар с требуемыми значениями
POST   {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token aa233d4314397c16eacb0bf09d1a139864a4ffa1

{
  "orderitem": {
    "order_id": 2,
    "productinfo": {
      "name_product": "Смартфон Apple iPhone XR 256GB (красный)",
      "name_shop": "Связной"
    },
    "quantity": 2
  }
}

###

# Удалить товар из корзины
DELETE {{baseUrl}}/basket/2/
Content-Type: application/json
Authorization: Token aa233d4314397c16eacb0bf09d1a139864a4ffa1

###

# Изменить количество товара в корзине
PATCH  {{baseUrl}}/basket/5/
Content-Type: application/json
Authorization: Token aa233d4314397c16eacb0bf09d1a139864a4ffa1

{
  "quantity": 1
}
